### PR TITLE
inject clientContext to served function on dev-server

### PR DESCRIPTION
**Pull request by joe-re**
Inject decoded information to served function on dev-server as same as production.
Actually it's difficult to verify access_token, so it's only inject decoded information.
but I think that is enough on development to check Netlify identify roles.

### CODE REVIEW

**Comment by joe-re** [comment]
ref: #51

**Comment by joe-re** [comment]
can anyone review this?
I feel this is highly needed to development on local..

**Comment by 8eecf0d2** [comment]
I'm using this now within Netlify and can see OP's reasoning, have added it to https://github.com/8eecf0d2/netlify-local/commit/6e20738313c584c1b215a466cd5214f7d405cbf3 based on this PR and implementation lines up with Netlify.

**Comment by sw-yx** [comment]
interesting. i have more context now and would like this too. will review in a few days as am ooo right now

**Comment by sw-yx** [comment]
hey @jcolbyfisher i like it too :) merging. can always work on docs later.

**Pull request merged**
