### PR TITLE
webpack-merge v5

### PR DESCRIPTION
**Pull request by bpinto**
- [x] Upgrades [webpack-merge](https://github.com/survivejs/webpack-merge) to latest.
- [x] Add a test covering plugins merge.

Disclaimer: I did not reimplement `merge.smart` because we may not need it. I thought it would be better to keep it simple and in case someone has a special need then we work on the code to handle that instead of potentially add unnecessary code.

### CODE REVIEW

**Comment by bpinto** [comment]
@erezrokah I've notice I hadn't run `npm run format` right before my last commit, so I've done it and pushed. Could you enable the workflow to run again? Thank you!

**Comment by bpinto** [comment]
@erezrokah have you had the time to review this PR? Is there any change you would like to see me doing?

**Comment by erezrokah** [comment]
Hi @bpinto, sorry for the delay here - can you detail the changes between `merge` and `merge.smart`?
This might be a breaking change (as well as https://github.com/netlify/netlify-lambda/pull/492) so we'll need to put it under a major version bump

**Comment by bpinto** [comment]
I'll share some links that explain how `merge.smart` used to work, it's a little

This is the [commit](https://github.com/survivejs/webpack-merge/commit/1c1c2f1e4748da74854a7eec3ab5b676f56b9835) that removed `merge.smart` method from [webpack-merge](https://github.com/survivejs/webpack-merge) library.

This is the docs for the removed method:

> _webpack-merge_ tries to be smart about merging loaders when `merge.smart` is used. Loaders with matching rule fields, including `test/enforce/include/exclude`, will be merged into a single loader value.

The standard webpack configuration that is used is very simple: https://github.com/netlify/netlify-lambda/blob/2493319f89c64178070bcfb5abe575964d2b3b02/lib/build.js#L137-L177

The only option I thought we could have an issue with the basic `merge` was the `module.rules` however looking at the old docs that does not appear to be the case. As far as I could see, we did not need the `smart` merge. That said, it's possible I've missed something and in that case we would need to tweak the merge strategy to handle any incompatibility issue that may arise.

By bumping the major version, I think that possible backwards incompatibility problem is reduced as most projects using this won't have issues after running a regular `npm update`.

**Comment by bpinto** [comment]
P.S.: I've rebased code on top of latest main.

**Comment by bpinto** [comment]
@erezrokah Sorry to ping you, but I'd love to see this PR merged :)

**Comment by bpinto** [comment]
Any news? Thank you!

**Comment by bpinto** [comment]
Any updates?

**Comment by laurentlaporte** [comment]
Why is this not merged?

**Comment by danez** [comment]
We are [deprecating](https://github.com/netlify/netlify-lambda/pull/606) `netlify-lambda` and therefore won't need this PR anymore. Thanks for your contributions and sorry it wasn't used.

**Pull request closed without merging**
