### PR TITLE
Doc improvements + small updates (webpack 4)

### PR DESCRIPTION
**Pull request by Offirmo**

### CODE REVIEW

**Comment by sw-yx** [comment]
thanks for the PR - we will roll this into https://github.com/netlify/netlify-lambda/pull/15 soon

**Comment by sw-yx** [comment]
thank you for this Offirmo! pulled your Readme changes here https://github.com/netlify/netlify-lambda/commit/32099761087cc2b0ee5708ea2dacbdb34da03a09 and I'm not sure about the node and error message but we can handle that in a separate update if necessary.

**Comment by Offirmo** [comment]
@sw-yx 

1) the node version was a bother, it should be the most recent stable, it's 100% gain 0% loss here. If AWS supports it, why not using the latest stable?

2) the error message corresponds to a case I was bitten by. Currently there is a failure but no clear message if the build finds no file to transpile.

**Comment by Offirmo** [comment]
@sw-yx P.S. thanks for your awesome work and tool!

**Comment by sw-yx** [comment]
i think we have addressed your concerns here - if any thing else you'd like to see changed please open an issue!

**Pull request closed without merging**
