### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by mottox2**
I upgrade to babel7 because I want to use `@babel/preset-typescript` that depends on babel7.

reference: https://babeljs.io/docs/en/next/v7-migration

### CODE REVIEW

**Comment by Offirmo** [comment]
can't wait for babel 7 to be official.

**Comment by sw-yx** [comment]
thanks for the PR - we will roll this into https://github.com/netlify/netlify-lambda/pull/15 soon

**Comment by nunoarruda** [comment]
I would like to see TypeScript support too 👍

**Comment by sw-yx** [comment]
Hi all,  we've upgraded to babel 7 officially! thank you for all your patience.

**Pull request closed without merging**
