### PR TITLE
merge current build context environment vars for lambda build

### LINKED ISSUE #59: environment context variables do not override build variables
If you define environment variables in the netlify.toml only the `build.environment` variables are being used.

Eg:
```
[build.environment]
  GREETING="Hello World! I am a variable set in a .env file"

# When building on the production environment this variable will NOT be used.
[context.production.environment]
  GREETING="production greeting"
```

### PR DESCRIPTION
**Pull request by shmargum**
resolves #59

### CODE REVIEW

**Comment by shmargum** [comment]
resolves #59

**Comment by 8eecf0d2** [comment]
Might be worth splitting out to a context merging method to set all options (not just environment) with support for branch specific contexts and the special context `branch-deploy`. Don't see a need to support `deploy-preview` since PR's aren't a thing locally and would use the special `branch-deploy` context if pulled anyway.

Based on [docs](https://www.netlify.com/docs/netlify-toml-reference/#deploy-contexts), given the following config and run within a git branch called `foo-branch`:
```toml
[build]
  publish = "/default"
[build.environment]
  SOME_VAR = true
[context.branch-deploy]
  publish = "/branch-deploy"
[context.branch-deploy.environment]
  SOME_VAR = false
[context.foo-branch]
  publish = "/foo-branch"
[context.foo-branch.environment]
  SOME_OTHER_VAR = 10
```

We should end up with:
```json
{
  "build": {
    "publish": "/foo-branch",
    "environment": {
      "SOME_VAR": false,
      "SOME_OTHER_VAR": 10,
    }
  }
}
```

**Comment by sw-yx** [comment]
sorry for late response - i was on holiday - i see theres also some desire to use the BRANCH env var: https://github.com/netlify/netlify-lambda/issues/59#issuecomment-450229263 - but i dont see that as a blocker to merge this.

up to your discretion on this one @8eecf0d2, i dont feel too strongly about it

**Comment by shmargum** [comment]
i've updated this to use the branch config
i'd love to add a test but theres no testing framework set up yet

**Comment by sw-yx** [comment]
awesome - ive been wondering about tests too and should probably get that going at some point. just wasnt built into it from the start.

**Comment by shmargum** [comment]
I've added some tests as well as a travis yml in #94
don't know if this is what you had in mind; but you can see the travis build successfully running the test on my fork:
https://github.com/shmargum/netlify-lambda/pull/1
if an admin for this repo enables travis ci then you would also see the tests run on #94

**Comment by sw-yx** [comment]
wow! nice! very kind of you! I'll go do travis (i've only done it once before... long time ago)

**Comment by shmargum** [comment]
This is included in #94

**Pull request closed without merging**
