### PR TITLE
Add flag to not use relative .babelrc config

### PR DESCRIPTION
**Pull request by omonk**
Based upon this issue https://github.com/netlify/netlify-lambda/issues/152

I'm not sure how this package is tested locally but my process was: 

`yarn add babel-preset-gatsby`

add a .babelrc in the root
```json
{
  "presets": ["babel-preset-gatsby"],
}
```

add `functions/handle.js` file with basic lambda 
```javacript
exports.handler = async () => {
  return {
    statusCode: 200,
    body: 'yay'
  }
}
```

add `netlify.toml` 
```toml
[build]
  functions = "./output"
```

to have the command error run:  `bin/cmd.js build functions/`

You should get and error that looks something along the lines of this: 
```
`babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI.
```

to have the command pass run: `bin/cmd.js build --babelrc false functions/`

### Can't you just set this babelrc: false opt in a custom webpack config?
I tried that but found that the webpackmerge library doesn't dedupe the two babel-loader rules so you end up with two babel-loader configs, one of which includes the root .babelrc

### CODE REVIEW

**Comment by sw-yx** [comment]
good enough for me. i still feel like we havent really addressed the issue of the mismatch between netlify lambda and the real deployment environment.

**Comment by sw-yx** [comment]
v1.4.10

**Comment by omonk** [comment]
@sw-yx what kind of differences do you have in mind? My build step in netlify is to run gatsby build and netlify-lambda build in parallel. This PR should help me with the issues I've been experiencing but happy to help out if you can shed any light into the netlify production environment and how you'd like to align!

**Comment by sw-yx** [comment]
i have no idea to be honest. i will just keep this in mind for now and come back to it when i figure out what it is. sorry i dont have a better answer.

**Pull request merged**
