### PR TITLE
Removed base-64 package in favour of node Buffer

### PR DESCRIPTION
**Pull request by 8eecf0d2**
I haven't read much about the [base-64 package](https://www.npmjs.com/package/base-64) but it's usage in **netlify-lambda** must be incorrect or not doing what's expected.

Switched to node `Buffer` instead and _afaict_ it should be doing the same thing, but for whatever reason `Buffer` works and `base-64` doesn't 🤷‍♂️

#26

### CODE REVIEW

**Comment by sw-yx** [comment]
thanks Brod. will circulate for review here

**Comment by 8eecf0d2** [comment]
I'm also a bit lost regarding this feature..

As far as responses, the following _should_ return a png to the browser - changing `isBase64Encoded` to `false` should return a the `base64` string.

```js
import * as path from "path";
import * as fs from "fs";

export const handler = async (request, context, callback) => {

  const pngBuffer = fs.readFileSync(path.join(process.cwd(), "dist/image.png"));
  
  return callback(null, {
    statusCode: 200,
    body: pngBuffer.toString("base64"),
    isBase64Encoded: true,
  })
}
```

As far as request's go, [Netlify Functions docs](https://www.netlify.com/docs/functions/#javascript-lambda-functions) mentions:

```js
{
  ...
  "isBase64Encoded": "A boolean flag to indicate if the applicable request payload is Base64-encode"
}
```

Which I'm guessing from the previous implementation worked correctly(?) although I have no means to test it right now.

**Comment by bcomnes** [comment]
cc @biilmann any insight on whats going on here?

**Comment by sw-yx** [comment]
accepting as it seems to be the better way but not sure if it's actually fixing #26 .

**Pull request merged**
