### PR TITLE
[WIP] Update to Babel 7

### PR DESCRIPTION
**Pull request by biilmann**
This updates to Babel 7 and webpack 4

### CODE REVIEW

**Comment by leonardodino** [comment]
based on [this pool](https://twitter.com/left_pad/status/821551189166878722) maybe we must update to `@babe/core` and other scoped packages?

it's seems to be the way forward on Babel 7. I even have to install it as a peer dependency, right now.

---

dependency error using `yarn@1.5.1` & `netlify-lambda@1.0.0-babel-7-beta`.
<details><summary> expand log </summary><p>

```
Building functions
Hash: f1fb444fa034b7754791
Version: webpack 4.2.0
Time: 223ms
Built at: 2018-3-27 01:54:33
   Asset      Size  Chunks  Chunk Names
index.js  1.53 KiB       0  index
Entrypoint index = index.js
   [0] ./index.js 959 bytes {0} [built] [failed] [1 error]

ERROR in ./index.js
Module build failed: Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/babel-loader/lib/transform.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/babel-loader/lib/cache.js:24:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

</p></details>

**Comment by Saeris** [comment]
Yes, you need to use the scoped packages.

Also, you can pass on individually including the following:
- `transform-class-properties`
- `transform-object-assign`
- `transform-object-rest-spread`

And instead go with 
- `@babel/preset-stage-3`

Which will includes class properties and rest-spread. Object-assign is included in preset-env.

Although personally I would go with stage-0, which includes all of the different proposal stages, which covers a wide range of use-cases. Just my two cents.

**Comment by leonardodino** [comment]
I would advise against using an experimental stage, especially for this kind of stuff. better to have resilient, and documented, standards, users can bypass it via `.babelrc` anyways.

**Comment by Saeris** [comment]
Well if you want to do things that way, you will have to include the following deps:

[`@babel/plugin-proposal-object-rest-spread`](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-object-rest-spread)
[`@babel/plugin-proposal-class-properties`](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties)
[`@babel/plugin-transform-object-assign`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-assign)

**Comment by sw-yx** [comment]
Hi all, we've upgraded to babel 7 officially! thank you for all your patience.

**Pull request closed without merging**
