### PR TITLE
Enable function invocation timeout using Promise.race

### PR DESCRIPTION
**Pull request by naipath**
This PR resolves the issue as described in #45 using Promise.race.
Invocation timeout can be configured using the flag `-t` or `--timeout` with a default of 10 seconds.

### CODE REVIEW

**Comment by naipath** [comment]
@sw-yx Happy to help! By all means add some docs and release 👍

**Comment by sw-yx** [comment]
v 1.4.0 https://github.com/netlify/netlify-lambda/releases/tag/1.4.0

**Comment by kamal-hossain** [comment]
Hey! I am trying to add set the time out for 30 minutes. So I have added the flag at my **package.json** file

`"scripts": {
    "lambda-serve": "netlify-lambda serve functions --timeout 1800",
  },`

But is is not working. If you guys kind enough to tell me how to use the `--timeout` in **netlify-lambda** then it will be helpful.

**Comment by erezrokah** [comment]
@kamal-hossain, I would suggest opening a new issue with a reproduction

**Pull request merged**
